spring:
  devtools:
    restart:
      aditional-paths: src/main/java
  application:
    name: score-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
  datasource:
    driver-class-name: org.postgresql.Driver
    dbname: postgres
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:5432/${POSTGRES_DB_SCORE}?useSSL=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  sql:
    init:
      platform: postgres
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


