apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  # Student database
  POSTGRES_DB_USER: userdb
  # Installment database
  POSTGRES_DB_INSTALLMENT: installmentdb
  # Score database
  POSTGRES_DB_SCORE: scoredb