server:
  port: 8081
spring:
  application:
    name: backend-config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/umibana/microservices-webapp
          search-paths: "config-data"